services:
  application:
    container_name: treat-service
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    env_file: .env
    depends_on:
      - redis
    networks:
      - treat-net

  redis:
    image: redis
    container_name: treat-redis
    ports:
      - "6379:6379"
    networks:
      - treat-net

networks:
  treat-net: